export type RPMBoneName =
    | "Hips"
    | "Spine"
    | "Spine1"
    | "Spine2"
    | "Neck"
    | "Head"
    | "HeadTop_End"
    | "LeftEye"
    | "RightEye"
    | "LeftShoulder"
    | "LeftArm"
    | "LeftForeArm"
    | "LeftHand"
    | "LeftHandThumb1"
    | "LeftHandThumb2"
    | "LeftHandThumb3"
    | "LeftHandThumb4"
    | "LeftHandIndex1"
    | "LeftHandIndex2"
    | "LeftHandIndex3"
    | "LeftHandIndex4"
    | "LeftHandMiddle1"
    | "LeftHandMiddle2"
    | "LeftHandMiddle3"
    | "LeftHandMiddle4"
    | "LeftHandRing1"
    | "LeftHandRing2"
    | "LeftHandRing3"
    | "LeftHandRing4"
    | "LeftHandPinky1"
    | "LeftHandPinky2"
    | "LeftHandPinky3"
    | "LeftHandPinky4"
    | "RightShoulder"
    | "RightArm"
    | "RightForeArm"
    | "RightHand"
    | "RightHandThumb1"
    | "RightHandThumb2"
    | "RightHandThumb3"
    | "RightHandThumb4"
    | "RightHandIndex1"
    | "RightHandIndex2"
    | "RightHandIndex3"
    | "RightHandIndex4"
    | "RightHandMiddle1"
    | "RightHandMiddle2"
    | "RightHandMiddle3"
    | "RightHandMiddle4"
    | "RightHandRing1"
    | "RightHandRing2"
    | "RightHandRing3"
    | "RightHandRing4"
    | "RightHandPinky1"
    | "RightHandPinky2"
    | "RightHandPinky3"
    | "RightHandPinky4"
    | "LeftUpLeg"
    | "LeftLeg"
    | "LeftFoot"
    | "LeftToeBase"
    | "LeftToe_End"
    | "RightUpLeg"
    | "RightLeg"
    | "RightFoot"
    | "RightToeBase"
    | "RightToe_End";

export type PoseLandmarkName =
    | "nose"
    | "leftEyeInner"
    | "leftEye"
    | "leftEyeOuter"
    | "rightEyeInner"
    | "rightEye"
    | "rightEyeOuter"
    | "leftEar"
    | "rightEar"
    | "mouthLeft"
    | "mouthRight"
    | "leftShoulder"
    | "rightShoulder"
    | "leftElbow"
    | "rightElbow"
    | "leftWrist"
    | "rightWrist"
    | "leftPinky"
    | "rightPinky"
    | "leftIndex"
    | "rightIndex"
    | "leftThumb"
    | "rightThumb"
    | "leftHip"
    | "rightHip"
    | "leftKnee"
    | "rightKnee"
    | "leftAnkle"
    | "rightAnkle"
    | "leftHeel"
    | "rightHeel"
    | "leftFootIndex"
    | "rightFootIndex";

export const PoseLandmarkNameIndex: {
    Nose: 0,
    LeftEyeInner: 1,
    LeftEye: 2,
    LeftEyeOuter: 3,
    RightEyeInner: 4,
    RightEye: 5,
    RightEyeOuter: 6,
    LeftEar: 7,
    RightEar: 8,
    MouthLeft: 9,
    MouthRight: 10,
    LeftShoulder: 11,
    RightShoulder: 12,
    LeftElbow: 13,
    RightElbow: 14,
    LeftWrist: 15,
    RightWrist: 16,
    LeftPinky: 17,
    RightPinky: 18,
    LeftIndex: 19,
    RightIndex: 20,
    LeftThumb: 21,
    RightThumb: 22,
    LeftHip: 23,
    RightHip: 24,
    LeftKnee: 25,
    RightKnee: 26,
    LeftAnkle: 27,
    RightAnkle: 28,
    LeftHeel: 29,
    RightHeel: 30,
    LeftFootIndex: 31,
    RightFootIndex: 32,
} = {
    Nose: 0,
    LeftEyeInner: 1,
    LeftEye: 2,
    LeftEyeOuter: 3,
    RightEyeInner: 4,
    RightEye: 5,
    RightEyeOuter: 6,
    LeftEar: 7,
    RightEar: 8,
    MouthLeft: 9,
    MouthRight: 10,
    LeftShoulder: 11,
    RightShoulder: 12,
    LeftElbow: 13,
    RightElbow: 14,
    LeftWrist: 15,
    RightWrist: 16,
    LeftPinky: 17,
    RightPinky: 18,
    LeftIndex: 19,
    RightIndex: 20,
    LeftThumb: 21,
    RightThumb: 22,
    LeftHip: 23,
    RightHip: 24,
    LeftKnee: 25,
    RightKnee: 26,
    LeftAnkle: 27,
    RightAnkle: 28,
    LeftHeel: 29,
    RightHeel: 30,
    LeftFootIndex: 31,
    RightFootIndex: 32,
};
